services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    container_name: nestjs-tests
    env_file:
      - .env.test
    depends_on:
      - postgres
    command: sh -c "pnpm exec prisma migrate deploy && pnpm run test && pnpm run test:e2e"
  postgres:
    image: postgres
    container_name: postgres-e2e
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5435:5432'
    tmpfs: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
