services:
  nestjs-api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: sh -c "
      pnpm exec prisma migrate deploy &&
      node dist/main"
    container_name: nestjs-api
    restart: 'always'
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: 'no'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
