export const mockedRecipes = [
  {
    title: 'Gazpacho',
    description: 'Spicy and flavorful.',
    cookingTime: 41,
    ingredients: [
      'chicken',
      'tomatoes',
      'milk',
      'garlic',
      'vinegar',
      'beef',
      'thyme',
      'olive oil',
      'sugar',
    ],
  },
  {
    title: "Shepherd's Pie",
    description: 'A family favorite.',
    cookingTime: 60,
    ingredients: [
      'garlic',
      'mushrooms',
      'butter',
      'basil',
      'mozzarella',
      'milk',
      'beans',
      'bell peppers',
    ],
  },
  {
    title: 'Shakshuka',
    description: 'Savory and satisfying.',
    cookingTime: 58,
    ingredients: ['salmon', 'ginger', 'potatoes', 'cream', 'noodles', 'sugar'],
  },
  {
    title: 'Eggplant Parmesan',
    description: 'Spicy and flavorful.',
    cookingTime: 117,
    ingredients: [
      'mushrooms',
      'chicken',
      'beef',
      'bell peppers',
      'pepper',
      'eggplant',
      'noodles',
      'salt',
    ],
  },
  {
    title: 'Lentil Soup',
    description: 'Spicy and flavorful.',
    cookingTime: 15,
    ingredients: [
      'salt',
      'soy sauce',
      'onions',
      'olive oil',
      'mushrooms',
      'ginger',
      'basil',
      'pepper',
    ],
  },
  {
    title: 'Tuna Casserole',
    description: 'A classic and hearty dish.',
    cookingTime: 35,
    ingredients: [
      'parmesan',
      'mozzarella',
      'mushrooms',
      'beans',
      'lime',
      'cream',
    ],
  },
  {
    title: 'Pad Thai',
    description: 'A classic and hearty dish.',
    cookingTime: 36,
    ingredients: [
      'tomatoes',
      'lime',
      'bell peppers',
      'potatoes',
      'vinegar',
      'basil',
      'cream',
      'soy sauce',
      'oregano',
      'garlic',
    ],
  },
  {
    title: 'Gumbo',
    description: 'Perfect for a weeknight dinner.',
    cookingTime: 11,
    ingredients: [
      'eggplant',
      'butter',
      'onions',
      'corn',
      'cream',
      'celery',
      'beef',
    ],
  },
  {
    title: 'Garlic Butter Shrimp',
    description: 'Savory and satisfying.',
    cookingTime: 21,
    ingredients: [
      'potatoes',
      'onions',
      'milk',
      'mushrooms',
      'chicken',
      'mozzarella',
      'olive oil',
    ],
  },
  {
    title: 'Chicken Curry',
    description: 'Perfect for a weeknight dinner.',
    cookingTime: 53,
    ingredients: ['bell peppers', 'corn', 'olive oil', 'cream', 'celery'],
  },
  {
    title: 'Fettuccine Bolognese',
    description: 'Spicy and flavorful.',
    cookingTime: 14,
    ingredients: [
      'bell peppers',
      'onions',
      'garlic',
      'eggplant',
      'celery',
      'beans',
      'shrimp',
      'chicken',
      'carrots',
    ],
  },
  {
    title: 'Vegetable Stir Fry',
    description: 'Perfect for a weeknight dinner.',
    cookingTime: 49,
    ingredients: [
      'mozzarella',
      'olive oil',
      'milk',
      'chicken',
      'carrots',
      'butter',
      'potatoes',
      'pepper',
      'shrimp',
    ],
  },
  {
    title: 'Bulgogi',
    description: 'Healthy and delicious.',
    cookingTime: 89,
    ingredients: [
      'celery',
      'soy sauce',
      'carrots',
      'bell peppers',
      'tomatoes',
      'thyme',
      'flour',
      'cream',
      'rice',
      'lemon',
    ],
  },
  {
    title: 'Enchiladas',
    description: 'A family favorite.',
    cookingTime: 78,
    ingredients: [
      'vinegar',
      'lime',
      'chicken',
      'mozzarella',
      'basil',
      'noodles',
      'mushrooms',
      'tomatoes',
      'zucchini',
      'ginger',
    ],
  },
  {
    title: 'Croque Monsieur',
    description: 'A creamy, rich recipe.',
    cookingTime: 47,
    ingredients: [
      'noodles',
      'sugar',
      'butter',
      'lime',
      'cabbage',
      'salt',
      'chicken',
      'thyme',
      'ginger',
      'celery',
    ],
  },
  {
    title: 'Pancakes',
    description: 'A family favorite.',
    cookingTime: 64,
    ingredients: ['potatoes', 'oregano', 'cabbage', 'milk', 'beans', 'shrimp'],
  },
  {
    title: 'Tuna Salad',
    description: 'A classic and hearty dish.',
    cookingTime: 101,
    ingredients: ['celery', 'cabbage', 'lemon', 'butter', 'shrimp'],
  },
  {
    title: 'Grilled Salmon',
    description: 'A classic and hearty dish.',
    cookingTime: 31,
    ingredients: ['salmon', 'shrimp', 'garlic', 'flour', 'oregano'],
  },
  {
    title: 'Baked Ziti',
    description: 'Spicy and flavorful.',
    cookingTime: 67,
    ingredients: [
      'flour',
      'butter',
      'soy sauce',
      'beef',
      'spinach',
      'eggplant',
      'tomatoes',
      'vinegar',
      'mozzarella',
      'basil',
    ],
  },
  {
    title: 'Chili Con Carne',
    description: 'Perfect for a weeknight dinner.',
    cookingTime: 82,
    ingredients: [
      'ginger',
      'carrots',
      'corn',
      'zucchini',
      'rice',
      'sugar',
      'cream',
      'parmesan',
      'oregano',
      'pepper',
    ],
  },
  {
    title: 'Teriyaki Chicken',
    description: 'A classic and hearty dish.',
    cookingTime: 119,
    ingredients: [
      'celery',
      'chicken',
      'parmesan',
      'onions',
      'beans',
      'salmon',
      'eggplant',
      'lime',
      'cream',
      'mushrooms',
    ],
  },
  {
    title: 'Beef Stroganoff',
    description: 'Healthy and delicious.',
    cookingTime: 80,
    ingredients: ['beans', 'mushrooms', 'cabbage', 'celery', 'shrimp'],
  },
  {
    title: 'Ratatouille',
    description: 'A classic and hearty dish.',
    cookingTime: 109,
    ingredients: [
      'mushrooms',
      'thyme',
      'eggplant',
      'celery',
      'ginger',
      'bell peppers',
      'salmon',
    ],
  },
  {
    title: 'Omelette',
    description: 'Perfect for a weeknight dinner.',
    cookingTime: 76,
    ingredients: [
      'milk',
      'pepper',
      'onions',
      'ginger',
      'lemon',
      'parmesan',
      'mushrooms',
      'butter',
      'olive oil',
    ],
  },
  {
    title: 'Fish Tacos',
    description: 'A family favorite.',
    cookingTime: 95,
    ingredients: [
      'corn',
      'oregano',
      'flour',
      'zucchini',
      'pepper',
      'spinach',
      'vinegar',
      'thyme',
      'milk',
      'tomatoes',
    ],
  },
  {
    title: 'Spaghetti Carbonara',
    description: 'Quick and easy to make.',
    cookingTime: 14,
    ingredients: [
      'chicken',
      'cabbage',
      'salt',
      'onions',
      'bell peppers',
      'spinach',
      'garlic',
      'salmon',
    ],
  },
  {
    title: 'Currywurst',
    description: 'Quick and easy to make.',
    cookingTime: 57,
    ingredients: [
      'vinegar',
      'onions',
      'tuna',
      'garlic',
      'corn',
      'salt',
      'parmesan',
      'mushrooms',
      'butter',
      'soy sauce',
    ],
  },
  {
    title: 'Kimchi Stew',
    description: 'Quick and easy to make.',
    cookingTime: 114,
    ingredients: [
      'rice',
      'oregano',
      'salt',
      'lemon',
      'tomatoes',
      'milk',
      'lime',
      'garlic',
    ],
  },
  {
    title: 'Beef Tacos',
    description: 'Savory and satisfying.',
    cookingTime: 29,
    ingredients: [
      'oregano',
      'parmesan',
      'chicken',
      'mozzarella',
      'potatoes',
      'thyme',
      'zucchini',
      'lime',
    ],
  },
  {
    title: 'Beef Wellington',
    description: 'Comfort food at its best.',
    cookingTime: 56,
    ingredients: [
      'shrimp',
      'tuna',
      'zucchini',
      'garlic',
      'flour',
      'salt',
      'corn',
      'thyme',
      'mushrooms',
      'celery',
    ],
  },
  {
    title: 'Fried Rice',
    description: 'Packed with fresh vegetables.',
    cookingTime: 71,
    ingredients: ['salmon', 'celery', 'ginger', 'thyme', 'sugar'],
  },
  {
    title: 'Turkey Sandwich',
    description: 'Packed with fresh vegetables.',
    cookingTime: 103,
    ingredients: [
      'mushrooms',
      'chicken',
      'mozzarella',
      'tomatoes',
      'vinegar',
      'parmesan',
    ],
  },
  {
    title: 'Mac and Cheese',
    description: 'Comfort food at its best.',
    cookingTime: 104,
    ingredients: [
      'mozzarella',
      'butter',
      'tomatoes',
      'ginger',
      'cabbage',
      'salmon',
      'salt',
      'pepper',
      'thyme',
    ],
  },
  {
    title: 'Chicken Noodle Soup',
    description: 'Savory and satisfying.',
    cookingTime: 12,
    ingredients: [
      'mushrooms',
      'cream',
      'vinegar',
      'salmon',
      'cabbage',
      'onions',
      'rice',
      'mozzarella',
    ],
  },
  {
    title: 'Clam Chowder',
    description: 'Savory and satisfying.',
    cookingTime: 100,
    ingredients: [
      'milk',
      'tuna',
      'beans',
      'sugar',
      'pepper',
      'soy sauce',
      'flour',
      'cream',
      'bell peppers',
      'salmon',
    ],
  },
  {
    title: 'Stuffed Peppers',
    description: 'A family favorite.',
    cookingTime: 57,
    ingredients: ['beef', 'bell peppers', 'celery', 'shrimp', 'cabbage'],
  },
  {
    title: 'Gnocchi with Pesto',
    description: 'A classic and hearty dish.',
    cookingTime: 86,
    ingredients: [
      'pepper',
      'corn',
      'eggplant',
      'beans',
      'zucchini',
      'rice',
      'parmesan',
      'salmon',
      'soy sauce',
      'flour',
    ],
  },
  {
    title: 'Cornbread',
    description: 'Savory and satisfying.',
    cookingTime: 108,
    ingredients: [
      'shrimp',
      'celery',
      'tuna',
      'salt',
      'salmon',
      'soy sauce',
      'garlic',
    ],
  },
  {
    title: 'Cabbage Rolls',
    description: 'Spicy and flavorful.',
    cookingTime: 87,
    ingredients: [
      'eggplant',
      'chicken',
      'pepper',
      'lemon',
      'cabbage',
      'tomatoes',
      'corn',
      'shrimp',
      'mushrooms',
    ],
  },
  {
    title: 'Zucchini Fritters',
    description: 'Packed with fresh vegetables.',
    cookingTime: 85,
    ingredients: [
      'tuna',
      'carrots',
      'milk',
      'sugar',
      'salmon',
      'noodles',
      'cabbage',
      'spinach',
      'potatoes',
      'corn',
    ],
  },
  {
    title: 'Pho',
    description: 'Spicy and flavorful.',
    cookingTime: 50,
    ingredients: [
      'eggplant',
      'onions',
      'salmon',
      'chicken',
      'lime',
      'soy sauce',
      'oregano',
      'parmesan',
      'tuna',
    ],
  },
  {
    title: 'BBQ Ribs',
    description: 'Quick and easy to make.',
    cookingTime: 61,
    ingredients: [
      'rice',
      'spinach',
      'milk',
      'pepper',
      'beef',
      'eggplant',
      'corn',
    ],
  },
  {
    title: 'Chicken Alfredo',
    description: 'Savory and satisfying.',
    cookingTime: 81,
    ingredients: [
      'potatoes',
      'eggplant',
      'olive oil',
      'noodles',
      'cream',
      'lemon',
      'carrots',
      'shrimp',
      'onions',
      'spinach',
    ],
  },
  {
    title: 'Meatloaf',
    description: 'Spicy and flavorful.',
    cookingTime: 33,
    ingredients: [
      'rice',
      'spinach',
      'shrimp',
      'celery',
      'basil',
      'potatoes',
      'corn',
      'vinegar',
      'beans',
      'carrots',
    ],
  },
  {
    title: 'Sloppy Joes',
    description: 'Healthy and delicious.',
    cookingTime: 78,
    ingredients: ['basil', 'lime', 'milk', 'flour', 'carrots', 'chicken'],
  },
  {
    title: 'Caesar Salad',
    description: 'Perfect for a weeknight dinner.',
    cookingTime: 76,
    ingredients: [
      'spinach',
      'oregano',
      'tuna',
      'tomatoes',
      'salt',
      'butter',
      'potatoes',
    ],
  },
  {
    title: 'Ceviche',
    description: 'Savory and satisfying.',
    cookingTime: 65,
    ingredients: ['beans', 'chicken', 'mozzarella', 'salmon', 'tomatoes'],
  },
  {
    title: 'Mushroom Risotto',
    description: 'A classic and hearty dish.',
    cookingTime: 22,
    ingredients: [
      'eggplant',
      'thyme',
      'vinegar',
      'garlic',
      'tomatoes',
      'potatoes',
      'soy sauce',
      'celery',
      'ginger',
    ],
  },
  {
    title: 'Lasagna',
    description: 'Perfect for a weeknight dinner.',
    cookingTime: 86,
    ingredients: ['celery', 'carrots', 'rice', 'onions', 'noodles', 'tuna'],
  },
  {
    title: 'Miso Soup',
    description: 'Spicy and flavorful.',
    cookingTime: 35,
    ingredients: ['thyme', 'onions', 'cream', 'rice', 'olive oil', 'lime'],
  },
];
